CREATE TABLE semantic_memory (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    animal VARCHAR(50) NOT NULL,
    species VARCHAR(100),
    climbs_trees BOOLEAN DEFAULT FALSE,
    group_behavior BOOLEAN DEFAULT FALSE,
    swimming_ability BOOLEAN DEFAULT FALSE,
    flight_ability BOOLEAN DEFAULT FALSE,
    toxicity BOOLEAN DEFAULT FALSE,
    avoidance_tendency BOOLEAN DEFAULT FALSE,
    aggression_tendency BOOLEAN DEFAULT FALSE,
    risk_level VARCHAR(10) CHECK (risk_level IN ('low', 'medium', 'high')),
    speed VARCHAR(10) CHECK (speed IN ('slow', 'medium', 'fast')),
    vision_sensitivity VARCHAR(10) CHECK (vision_sensitivity IN ('low', 'medium', 'high')),
    hearing_sensitivity VARCHAR(10) CHECK (hearing_sensitivity IN ('low', 'medium', 'high')),
    color_weights JSONB,
    shape_weights JSONB
);

CREATE TABLE model_output (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    animal VARCHAR(50) NOT NULL,
    predicted_behavior VARCHAR(100),
    action_plan TEXT
);

CREATE TABLE episodic_memory (
    id VARCHAR(50) PRIMARY KEY,
    animal VARCHAR(50) NOT NULL,
    impact INTEGER,
    event_date TIMESTAMP,
    context JSONB
);

INSERT INTO episodic_memory (id, animal, impact, event_date, context)
VALUES
  ('hs10', 'hognose snake', 0, '2023-07-20 23:10:00', '["Movie", "Mistaken Identity", "Mistook for venomous snake", "Fear"]'::jsonb),
  ('hs11', 'hognose snake', 1, '2025-08-18 18:40:00', '["Documentary", "Nose in captivity", "Digging", "Foraging"]'::jsonb),
  ('hs20', 'asian vine snake', 0, '2025-03-15 15:30:00', '["Documentary", "On a tree", "Camouflage color"]'::jsonb),
  ('hs21', 'asian vine snake', 1, '2025-04-18 10:20:00', '["YouTube", "Fast movement", "On a branch"]'::jsonb),
  ('hs30', 'corn snake', 0, '2025-02-22 12:10:00', '["Pet shop", "Captivity", "Human interaction"]'::jsonb),
  ('hs31', 'corn snake', 0, '2025-05-09 17:00:00', '["Field Guide", "Bright patterns", "Non-venomous"]'::jsonb),
  ('hs40', 'boomsland', 1, '2025-03-12 19:00:00', '["Documentary", "Flashy patterns", "Mistaken threat"]'::jsonb),
  ('hs41', 'boomsland', 0, '2025-06-03 20:15:00', '["YouTube", "Decorative", "Non-venomous"]'::jsonb),
  ('hs50', 'coral snake', 1, '2025-04-25 08:30:00', '["News", "Venomous", "Human bite"]'::jsonb),
  ('hs51', 'coral snake', 1, '2025-05-28 16:50:00', '["Field Guide", "Warning colors", "Red-yellow-black stripes"]'::jsonb),
  ('hs6', 'hognose snake', 0, '2025-03-10 21:00:00', '["Documentary", "Neck flattening", "Defensive posture", "TV"]'::jsonb),
  ('hs60', 'yellow rat snake', 1, '2025-02-18 11:20:00', '["Documentary", "Near farmland", "Rat hunting"]'::jsonb),
  ('hs61', 'yellow rat snake', 0, '2025-06-15 09:10:00', '["Field Guide", "Large snake", "Non-venomous"]'::jsonb),
  ('hs7', 'kingsnake', 0, '2025-04-02 22:15:00', '["YouTube", "Playing dead", "Flipping over belly", "Surprise"]'::jsonb),
  ('hs70', 'kingsnake', 1, '2025-03-09 18:40:00', '["Documentary", "Preys on other snakes", "Strong jaw"]'::jsonb),
  ('hs71', 'kingsnake', 1, '2025-07-11 13:20:00', '["YouTube", "Popular in captivity", "Pattern diversity"]'::jsonb),
  ('hs8', 'hognose snake', 0, '2025-05-05 14:00:00', '["YouTube", "Earthworm", "Frog diet", "Educational"]'::jsonb),
  ('hs80', 'viper', 1, '2025-02-28 22:00:00', '["News", "Triangular head", "Human bite case"]'::jsonb),
  ('hs81', 'viper', 1, '2025-05-19 14:30:00', '["Documentary", "Camouflage color", "Hidden habit"]'::jsonb),
  ('hs9', 'hognose snake', 1, '2025-06-12 19:30:00', '["Documentary", "Human interaction", "Arousing fear", "..."]'::jsonb),
  ('hs90', 'black mamba', 0, '2025-03-21 10:40:00', '["YouTube", "Fast speed", "Neurotoxin"]'::jsonb),
  ('hs91', 'black mamba', 1, '2025-06-07 21:00:00', '["News", "Death case", "Dangerous snake"]'::jsonb);

INSERT INTO semantic_memory
(animal, species, climbs_trees, group_behavior, swimming_ability, flight_ability,
 toxicity, avoidance_tendency, aggression_tendency,
 risk_level, speed, vision_sensitivity, hearing_sensitivity,
 color_weights, shape_weights)
VALUES
('snake', 'hognose snake',
 FALSE, FALSE, TRUE, FALSE, FALSE, TRUE, FALSE,
 'low', 'slow', 'medium', 'low',
 '{"brown":0.7,"cream":0.8,"black spots":0.9}'::jsonb,
 '{"short body":0.7,"small head":0.6,"upturned nose":1.0}'::jsonb),

('snake', 'asian vine snake',
 TRUE, FALSE, TRUE, FALSE, FALSE, TRUE, FALSE,
 'low', 'medium', 'high', 'low',
 '{"green":1.0,"light green":0.9}'::jsonb,
 '{"long body":0.8,"slender body":1.0,"pointed snout":0.9}'::jsonb),

('snake', 'corn snake',
 TRUE, FALSE, TRUE, FALSE, FALSE, TRUE, FALSE,
 'low', 'medium', 'medium', 'low',
 '{"red":0.8,"brown":0.6,"orange":1.0}'::jsonb,
 '{"stripes":0.6,"blotches":0.7,"checkerboard pattern":1.0}'::jsonb),

('snake', 'boomslang',
 TRUE, FALSE, TRUE, FALSE, FALSE, TRUE, FALSE,
 'low', 'medium', 'high', 'low',
 '{"green":1.0,"yellow":0.7}'::jsonb,
 '{"large eyes":1.0,"slender body":0.7}'::jsonb),

('snake', 'coral snake',
 TRUE, FALSE, TRUE, FALSE, TRUE, TRUE, FALSE,
 'high', 'medium', 'low', 'low',
 '{"red":1.0,"black":0.9,"yellow":0.9}'::jsonb,
 '{"slender body":0.7,"banded pattern":1.0}'::jsonb),

('snake', 'yellow rat snake',
 TRUE, FALSE, TRUE, FALSE, FALSE, TRUE, FALSE,
 'low', 'medium', 'medium', 'low',
 '{"brown":0.8,"yellow":1.0}'::jsonb,
 '{"stripes":0.7,"long body":0.8}'::jsonb),

('snake', 'kingsnake',
 TRUE, FALSE, TRUE, FALSE, FALSE, TRUE, FALSE,
 'low', 'medium', 'medium', 'medium',
 '{"red":0.6,"black":0.9,"white":0.8,"yellow":0.7}'::jsonb,
 '{"chain pattern":0.8,"banded pattern":1.0}'::jsonb),

('snake', 'viper',
 TRUE, FALSE, TRUE, FALSE, TRUE, TRUE, TRUE,
 'high', 'medium', 'medium', 'low',
 '{"gray":0.7,"black":0.6,"brown":0.8,"green":0.5}'::jsonb,
 '{"stripes":0.6,"blotches":0.6,"thick body":0.8,"triangular head":1.0}'::jsonb),

('snake', 'black mamba',
 TRUE, FALSE, TRUE, FALSE, TRUE, TRUE, TRUE,
 'high', 'fast', 'high', 'low',
 '{"gray":0.7,"black":1.0}'::jsonb,
 '{"very long":1.0,"slender body":0.8,"coffin-shaped head":0.9}'::jsonb);
